#!/bin/sh
# native/jnlua/repack.sh -- produce the ADDITIVE variant of jnlua.c.
#
#     sh native/jnlua/repack.sh <OC-JNLua> <out.c> [suffix] [class]
#
# WHAT THIS IS FOR.  native/lj52shim.h forces LUA_VERSION_NUM to 502, so
# jnlua.c's version chain picks
#
#     #define JNI_LUASTATE_CLASS "li/cil/repack/com/naef/jnlua/LuaState"
#     #define JNLUA_SUFFIX
#
# and the library we build exports Java_li_cil_repack_com_naef_jnlua_LuaState_*
# -- i.e. it IS OpenComputers' 5.2 native, replacing it.  That is exactly right
# for the benchmark harness, which substitutes the DLL wholesale via
# debug.forceNativeLibPathFirst, and it can never be the shipped mod: OC loads
# its own 5.2 native in preInit and binds that class to it, and two libraries
# cannot back one class.  See docs/research/shipping-model.md.
#
# The shipped mod is ADDITIVE.  OpenComputers already runs three VMs in one JVM
# without collision, because each binds a DIFFERENT class -- LuaState,
# LuaStateFiveThree, LuaStateFiveFour -- and JNI derives symbol names from the
# declaring class.  We become the fourth: LuaStateLuaJIT, generated by
# gen-luastate-subclass.py, backed by a library exporting
# Java_li_cil_repack_com_naef_jnlua_LuaStateLuaJIT_*.
#
# WHY A COPY AND NOT A -D.  The two #defines live in an unguarded
# `#if LUA_VERSION_NUM` chain (jnlua.c:42-53) with no arm for us and no #ifndef,
# so a -D cannot reach them, and the shim is force-included BEFORE jnlua.c, so
# it cannot get between the chain and the use sites either.  Rewriting a copy is
# the only route -- and it is precisely what a "repack" is: OC-JNLua itself is a
# repack of upstream com.naef.jnlua into li.cil.repack.com.naef.jnlua.
#
# WHAT IT COSTS THE "UNMODIFIED jnlua.c" CLAIM.  It narrows it rather than
# killing it.  The CHECKOUT stays pristine and build-native.sh's git-status
# assertion keeps its meaning; the claim becomes a statement about the INPUT to
# the repack.  What must never happen is a fork of jnlua.c's LOGIC: this script
# changes two macro values and nothing else, and verifies exactly that below.
set -u

[ $# -ge 2 ] || { echo "usage: repack.sh <OC-JNLua> <out.c> [suffix] [class]" >&2; exit 2; }
JNLUA=$1
OUT=$2
SUFFIX=${3:-LuaJIT}
CLASS=${4:-li/cil/repack/com/naef/jnlua/LuaState$SUFFIX}
SRC="$JNLUA/native/src/jnlua.c"

[ -f "$SRC" ] || { echo "repack.sh: no $SRC" >&2; exit 2; }

# The 5.2 arm as it stands upstream.  Anchored on both lines together so a
# reshaped chain cannot be half-substituted.
OLD_CLASS='#define JNI_LUASTATE_CLASS "li/cil/repack/com/naef/jnlua/LuaState"'
NEW_CLASS="#define JNI_LUASTATE_CLASS \"$CLASS\""

mkdir -p "$(dirname "$OUT")" || exit 1

awk -v oldc="$OLD_CLASS" -v newc="$NEW_CLASS" -v suf="$SUFFIX" '
  # Only inside the 502 arm: the 503/504 arms must be left exactly as they are,
  # or a future build for another version would silently inherit our names.
  /^#elif LUA_VERSION_NUM == 502$/ { in502 = 1 }
  /^#else$/                        { in502 = 0 }
  in502 && $0 == oldc              { print newc; subs_class++; next }
  in502 && /^#define JNLUA_SUFFIX/ { print "#define JNLUA_SUFFIX " suf; subs_suffix++; next }
  { print }
  END {
    if (subs_class != 1 || subs_suffix != 1) {
      printf("repack.sh: expected exactly one substitution of each inside the 502 arm, got class=%d suffix=%d\n",
             subs_class, subs_suffix) > "/dev/stderr"
      exit 1
    }
  }
' "$SRC" > "$OUT" || { echo "repack.sh: substitution failed -- has jnlua.c'\''s version chain changed shape?" >&2; rm -f "$OUT"; exit 1; }

# VERIFY, RATHER THAN TRUST THE SED.  Three properties, each of which has a
# plausible way to go wrong silently:
#   1. our names are present
#   2. the ORIGINAL 5.2 names are gone, so we cannot still be OC's native
#   3. NOTHING ELSE CHANGED -- exactly two differing lines against the input
grep -q "#define JNLUA_SUFFIX $SUFFIX" "$OUT" \
  || { echo "repack.sh: suffix not applied" >&2; exit 1; }
grep -q "#define JNI_LUASTATE_CLASS \"$CLASS\"" "$OUT" \
  || { echo "repack.sh: class not applied" >&2; exit 1; }
if grep -q "$OLD_CLASS" "$OUT"; then
  echo "repack.sh: the ORIGINAL 5.2 class string survives -- this library would still" >&2
  echo "           claim to be OpenComputers' own 5.2 native." >&2
  exit 1
fi
DIFFLINES=$(diff --strip-trailing-cr "$SRC" "$OUT" 2>/dev/null | grep -c "^[<>]")
if [ "$DIFFLINES" != "4" ]; then
  echo "repack.sh: expected exactly 4 diff lines (2 changed lines, each < and >)," >&2
  echo "           got $DIFFLINES.  A repack must change macro VALUES and nothing" >&2
  echo "           else; anything more is a fork of jnlua.c's logic." >&2
  diff "$SRC" "$OUT" | head -20 >&2
  exit 1
fi

echo "repack.sh: $(basename "$OUT")  suffix=$SUFFIX  class=$CLASS"
echo "repack.sh: exports will be Java_$(printf '%s' "$CLASS" | tr '/' '_')_*"
echo "repack.sh: 2 lines changed, jnlua.c logic untouched"
