package li.cil.repack.com.naef.jnlua;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

/**
 * The OC-LuaJIT LuaState: a fourth JNLua binding class alongside OC's own.
 *
 * GENERATED by native/jnlua/gen-luastate-subclass.py from OC-JNLua's
 * LuaState.java.  Do not edit; edit the generator and regenerate.
 *
 * JNI resolves a native to Java_<package>_<declaring class>_<method>, so
 * redeclaring the inherited natives here -- and only that -- gives our library
 * its own symbol family, Java_li_cil_repack_com_naef_jnlua_LuaStateLuaJIT_*.
 * That is how OpenComputers runs 5.2, 5.3 and 5.4 side by side in one JVM, and
 * it is what lets OC-LuaJIT be ADDITIVE rather than a replacement.
 *
 * No behavioural overrides, deliberately: we are 5.2-class, so the base class's
 * arith/gc enum numbering is already correct and inheriting it is the point.
 *
 * The nested LuaDebug is MANDATORY: jnlua.c JNI_OnLoad does
 * referenceclass(JNI_LUASTATE_CLASS "$LuaDebug") at :1741 and fails the
 * entire library load without it.  Emitting it as a SUBCLASS also makes
 * the base getName()/getNameWhat() dispatch to OUR natives.
 */
public class LuaStateLuaJIT extends LuaState {
	public LuaStateLuaJIT() {
		super();
	}

	public LuaStateLuaJIT(int memory) {
		super(memory);
	}

	/* ---- the 82 inherited natives, redeclared so they bind to OUR library ---- */

	@Override
	protected native int lua_integerwidth();

	@Override
	protected native int lua_pointerwidth();

	@Override
	protected native int lua_registryindex();

	@Override
	protected native String lua_version();

	@Override
	protected native int lua_versionnum();

	@Override
	protected native void lua_newstate(int apiversion, long luaState);

	@Override
	protected native void lua_close(boolean ownState);

	@Override
	protected native int lua_gc(int what, int data);

	@Override
	protected native void lua_openlib(int lib);

	@Override
	protected native void lua_load(InputStream inputStream, String chunkname, String mode) throws IOException;

	@Override
	protected native void lua_dump(OutputStream outputStream) throws IOException;

	@Override
	protected native void lua_pcall(int nargs, int nresults);

	@Override
	protected native void lua_getglobal(String name);

	@Override
	protected native void lua_setglobal(String name);

	@Override
	protected native void lua_pushboolean(boolean b);

	@Override
	protected native void lua_pushbytearray(byte[] b);

	@Override
	protected native void lua_pushinteger(long n);

	@Override
	protected native void lua_pushjavafunction(JavaFunction f);

	@Override
	protected native void lua_pushjavaobject(Object object);

	@Override
	protected native void lua_pushnil();

	@Override
	protected native void lua_pushnumber(double n);

	@Override
	protected native boolean lua_isboolean(int index);

	@Override
	protected native boolean lua_iscfunction(int index);

	@Override
	protected native boolean lua_isfunction(int index);

	@Override
	protected native boolean lua_isjavafunction(int index);

	@Override
	protected native boolean lua_isjavaobject(int index);

	@Override
	protected native boolean lua_isnil(int index);

	@Override
	protected native boolean lua_isnone(int index);

	@Override
	protected native boolean lua_isnoneornil(int index);

	@Override
	protected native boolean lua_isnumber(int index);

	@Override
	protected native boolean lua_isstring(int index);

	@Override
	protected native boolean lua_istable(int index);

	@Override
	protected native boolean lua_isthread(int index);

	@Override
	protected native int lua_compare(int index1, int index2, int operator);

	@Override
	protected native int lua_rawequal(int index1, int index2);

	@Override
	protected native int lua_rawlen(int index);

	@Override
	protected native boolean lua_toboolean(int index);

	@Override
	protected native byte[] lua_tobytearray(int index);

	@Override
	protected native long lua_tointeger(int index);

	@Override
	protected native Long lua_tointegerx(int index);

	@Override
	protected native JavaFunction lua_tojavafunction(int index);

	@Override
	protected native Object lua_tojavaobject(int index);

	@Override
	protected native double lua_tonumber(int index);

	@Override
	protected native Double lua_tonumberx(int index);

	@Override
	protected native long lua_topointer(int index);

	@Override
	protected native int lua_type(int index);

	@Override
	protected native int lua_absindex(int index);

	@Override
	protected native int lua_arith(int operator);

	@Override
	protected native void lua_concat(int n);

	@Override
	protected native int lua_copy(int fromIndex, int toIndex);

	@Override
	protected native int lua_gettop();

	@Override
	protected native void lua_len(int index);

	@Override
	protected native void lua_insert(int index);

	@Override
	protected native void lua_pop(int n);

	@Override
	protected native void lua_pushvalue(int index);

	@Override
	protected native void lua_remove(int index);

	@Override
	protected native void lua_replace(int index);

	@Override
	protected native void lua_settop(int index);

	@Override
	protected native void lua_createtable(int narr, int nrec);

	@Override
	protected native int lua_getsubtable(int idx, String fname);

	@Override
	protected native void lua_gettable(int index);

	@Override
	protected native void lua_getfield(int index, String k);

	@Override
	protected native void lua_newtable();

	@Override
	protected native int lua_next(int index);

	@Override
	protected native void lua_rawget(int index);

	@Override
	protected native void lua_rawgeti(int index, int n);

	@Override
	protected native void lua_rawset(int index);

	@Override
	protected native void lua_rawseti(int index, int n);

	@Override
	protected native void lua_settable(int index);

	@Override
	protected native void lua_setfield(int index, String k);

	@Override
	protected native int lua_getmetatable(int index);

	@Override
	protected native void lua_setmetatable(int index);

	@Override
	protected native int lua_getmetafield(int index, String k);

	@Override
	protected native void lua_newthread();

	@Override
	protected native int lua_resume(int index, int nargs);

	@Override
	protected native int lua_status(int index);

	@Override
	protected native int lua_ref(int index);

	@Override
	protected native void lua_unref(int index, int ref);

	@Override
	protected native LuaDebug lua_getstack(int level);

	@Override
	protected native int lua_getinfo(String what, LuaState.LuaDebug ar);

	@Override
	protected native int lua_tablesize(int index);

	@Override
	protected native void lua_tablemove(int index, int from, int to, int count);

	/**
	 * Our own activation record, REQUIRED by jnlua.c's JNI_OnLoad.
	 *
	 * It extends LuaState.LuaDebug for two reasons.  Covariance: our
	 * lua_getstack returns LuaDebug, which only overrides the base method if
	 * this is a subtype of the base return type.  And DISPATCH: the base's
	 * getName()/getNameWhat() call lua_debugname()/lua_debugnamewhat()
	 * virtually, so they land on the overrides below and therefore on OUR
	 * library -- without which a handle from our lua_getstack would be read
	 * by OpenComputers PUC code, i.e. type confusion across two VMs.
	 *
	 * super(_, false) deliberately: the base constructor guardian calls ITS
	 * OWN lua_debugfree, which binds to OpenComputers library.  We own it here.
	 */
	protected static class LuaDebug extends LuaState.LuaDebug {
		/** jnlua.c looks this up BY NAME on THIS class (GetFieldID, :1743); the
		  * base field of the same name is private and therefore not ours. */
		private long luaDebug;

		private Object finalizeGuardian;

		protected LuaDebug(long luaDebug, boolean ownDebug) {
			super(luaDebug, false);
			this.luaDebug = luaDebug;
			if (ownDebug) {
				finalizeGuardian = new Object() {
					@Override
					protected void finalize() {
						synchronized (LuaDebug.this) {
							lua_debugfree();
						}
					}
				};
			}
		}

		@Override
		protected native void lua_debugfree();

		@Override
		protected native String lua_debugname();

		@Override
		protected native String lua_debugnamewhat();

	}
}
